role_name: "cart"
server: "cart"
enable_app_version: "20"
disable_enable_app: "nodejs"
app_install:
  - { name: "nodejs" , version: ""}
user:
  - "roboshop"
dir_owner: "roboshop"
directory_path: "/app"
redis_ip: "10.0.2.51"
catalogue_ip: "10.0.2.80"
systemd_app_name: "cart"
microservice_name: "cart"

