role_name: "shipping"
server: "shipping"
microservice_name: "shipping"
app_install:
  - { name: "maven", version: ""}
  - { name: "mysql", version: ""}
schemas:
  - "schema"
  - "app-user"
  - "master-data"
user:
  - "roboshop"
dir_owner: "roboshop"
directory_path: "/app"
cart_ip: "10.0.2.17"
mysql_ip: "10.0.2.217"
systemd_app_name: "shipping"
rb_password: "RoboShop@1"