role_name: user
server: user
app_install:
  - { name: "nodejs" , version: "" }
disable_enable_app: "nodejs"
enable_app_version: "20"
user:
  - "roboshop"
dir_owner: "roboshop"
directory_path: "/app"
redis_ip: "10.0.2.51"
mongo_ip: "10.0.2.20"
systemd_app_name: "user"